services:
  load_balancer:
    build: ./load_balancer
    image: ds-load-balancer:latest
    container_name: load_balancer
    ports:
      - "5000:5000"
    environment:
      N: "3"
      SERVER_IMAGE: ds-server:latest
      NETWORK_NAME: kaziii_net1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - load_balancer

networks:
  net1:
    name: kaziii_net1
